# Use the official phpMyAdmin 5.2 image
FROM phpmyadmin:5.2

COPY src /src

# Run initialization scripts
RUN chmod 755 -- /src/*.sh \
    && /src/install-cli-tools.sh \
    && /src/configure-apache.sh \
    && /src/configure-https.sh
