services:
  db:
    build: 
      dockerfile: Dockerfile-mariadb
    container_name: mariadb_s
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: onlineshop
      MYSQL_PASSWORD: geheim
      MYSQL_ROOT_HOST: "%"
      LANG: C.UTF-8
    ports:
      - "6033:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  php-apache:
    build: 
      dockerfile: Dockerfile-php
    container_name: webapp_s
    volumes:
      - ./webapp:/var/www/html
      - ./symfony:/home/symfony
    ports:
      - "8080:80"
      - "7443:443"
      - "8000:8000"
    environment:
      DB_HOST: db:3306
      DB_USER: onlineshop
      DB_NAME: onlineshop
      DB_PASSWORD: geheim
    restart: always
  phpmyadmin:
    build:
      dockerfile: Dockerfile-phpmyadmin
    container_name: pma_s
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: onlineshop
      PMA_PASSWORD: geheim
    restart: always
    ports:
      - 8082:80
      - 8443:443
volumes:
  dbdata:
networks:
  default:
    name: webnet_s
